/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_io_CommPortOwnershipListener */

#ifndef _Included_gnu_io_CommPortOwnershipListener
#define _Included_gnu_io_CommPortOwnershipListener
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_io_CommPortOwnershipListener_PORT_OWNED
#define gnu_io_CommPortOwnershipListener_PORT_OWNED 1L
#undef gnu_io_CommPortOwnershipListener_PORT_UNOWNED
#define gnu_io_CommPortOwnershipListener_PORT_UNOWNED 2L
#undef gnu_io_CommPortOwnershipListener_PORT_OWNERSHIP_REQUESTED
#define gnu_io_CommPortOwnershipListener_PORT_OWNERSHIP_REQUESTED 3L
#ifdef __cplusplus
}
#endif
#endif
