/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_io_RawPortEventListener */

#ifndef _Included_gnu_io_RawPortEventListener
#define _Included_gnu_io_RawPortEventListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
