/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_io_RawPortEvent */

#ifndef _Included_gnu_io_RawPortEvent
#define _Included_gnu_io_RawPortEvent
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_io_RawPortEvent_serialVersionUID
#define gnu_io_RawPortEvent_serialVersionUID 5516075349620653480LL
#undef gnu_io_RawPortEvent_DATA_AVAILABLE
#define gnu_io_RawPortEvent_DATA_AVAILABLE 1L
#undef gnu_io_RawPortEvent_OUTPUT_BUFFER_EMPTY
#define gnu_io_RawPortEvent_OUTPUT_BUFFER_EMPTY 2L
#undef gnu_io_RawPortEvent_CTS
#define gnu_io_RawPortEvent_CTS 3L
#undef gnu_io_RawPortEvent_DSR
#define gnu_io_RawPortEvent_DSR 4L
#undef gnu_io_RawPortEvent_RI
#define gnu_io_RawPortEvent_RI 5L
#undef gnu_io_RawPortEvent_CD
#define gnu_io_RawPortEvent_CD 6L
#undef gnu_io_RawPortEvent_OE
#define gnu_io_RawPortEvent_OE 7L
#undef gnu_io_RawPortEvent_PE
#define gnu_io_RawPortEvent_PE 8L
#undef gnu_io_RawPortEvent_FE
#define gnu_io_RawPortEvent_FE 9L
#undef gnu_io_RawPortEvent_BI
#define gnu_io_RawPortEvent_BI 10L
#ifdef __cplusplus
}
#endif
#endif
