/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_io_Configure__4 */

#ifndef _Included_gnu_io_Configure__4
#define _Included_gnu_io_Configure__4
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
