/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_io_RS485PortEvent */

#ifndef _Included_gnu_io_RS485PortEvent
#define _Included_gnu_io_RS485PortEvent
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_io_RS485PortEvent_serialVersionUID
#define gnu_io_RS485PortEvent_serialVersionUID 5516075349620653480LL
#undef gnu_io_RS485PortEvent_DATA_AVAILABLE
#define gnu_io_RS485PortEvent_DATA_AVAILABLE 1L
#undef gnu_io_RS485PortEvent_OUTPUT_BUFFER_EMPTY
#define gnu_io_RS485PortEvent_OUTPUT_BUFFER_EMPTY 2L
#undef gnu_io_RS485PortEvent_CTS
#define gnu_io_RS485PortEvent_CTS 3L
#undef gnu_io_RS485PortEvent_DSR
#define gnu_io_RS485PortEvent_DSR 4L
#undef gnu_io_RS485PortEvent_RI
#define gnu_io_RS485PortEvent_RI 5L
#undef gnu_io_RS485PortEvent_CD
#define gnu_io_RS485PortEvent_CD 6L
#undef gnu_io_RS485PortEvent_OE
#define gnu_io_RS485PortEvent_OE 7L
#undef gnu_io_RS485PortEvent_PE
#define gnu_io_RS485PortEvent_PE 8L
#undef gnu_io_RS485PortEvent_FE
#define gnu_io_RS485PortEvent_FE 9L
#undef gnu_io_RS485PortEvent_BI
#define gnu_io_RS485PortEvent_BI 10L
#ifdef __cplusplus
}
#endif
#endif
