/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_io_I2CPortEvent */

#ifndef _Included_gnu_io_I2CPortEvent
#define _Included_gnu_io_I2CPortEvent
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_io_I2CPortEvent_serialVersionUID
#define gnu_io_I2CPortEvent_serialVersionUID 5516075349620653480LL
#undef gnu_io_I2CPortEvent_DATA_AVAILABLE
#define gnu_io_I2CPortEvent_DATA_AVAILABLE 1L
#undef gnu_io_I2CPortEvent_OUTPUT_BUFFER_EMPTY
#define gnu_io_I2CPortEvent_OUTPUT_BUFFER_EMPTY 2L
#undef gnu_io_I2CPortEvent_CTS
#define gnu_io_I2CPortEvent_CTS 3L
#undef gnu_io_I2CPortEvent_DSR
#define gnu_io_I2CPortEvent_DSR 4L
#undef gnu_io_I2CPortEvent_RI
#define gnu_io_I2CPortEvent_RI 5L
#undef gnu_io_I2CPortEvent_CD
#define gnu_io_I2CPortEvent_CD 6L
#undef gnu_io_I2CPortEvent_OE
#define gnu_io_I2CPortEvent_OE 7L
#undef gnu_io_I2CPortEvent_PE
#define gnu_io_I2CPortEvent_PE 8L
#undef gnu_io_I2CPortEvent_FE
#define gnu_io_I2CPortEvent_FE 9L
#undef gnu_io_I2CPortEvent_BI
#define gnu_io_I2CPortEvent_BI 10L
#ifdef __cplusplus
}
#endif
#endif
