/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_io_CommPortEnumerator */

#ifndef _Included_gnu_io_CommPortEnumerator
#define _Included_gnu_io_CommPortEnumerator
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_io_CommPortEnumerator_debug
#define gnu_io_CommPortEnumerator_debug 0L
#ifdef __cplusplus
}
#endif
#endif
