/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_io_I2CPort */

#ifndef _Included_gnu_io_I2CPort
#define _Included_gnu_io_I2CPort
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_io_I2CPort_debug
#define gnu_io_I2CPort_debug 0L
#undef gnu_io_I2CPort_DATABITS_5
#define gnu_io_I2CPort_DATABITS_5 5L
#undef gnu_io_I2CPort_DATABITS_6
#define gnu_io_I2CPort_DATABITS_6 6L
#undef gnu_io_I2CPort_DATABITS_7
#define gnu_io_I2CPort_DATABITS_7 7L
#undef gnu_io_I2CPort_DATABITS_8
#define gnu_io_I2CPort_DATABITS_8 8L
#undef gnu_io_I2CPort_PARITY_NONE
#define gnu_io_I2CPort_PARITY_NONE 0L
#undef gnu_io_I2CPort_PARITY_ODD
#define gnu_io_I2CPort_PARITY_ODD 1L
#undef gnu_io_I2CPort_PARITY_EVEN
#define gnu_io_I2CPort_PARITY_EVEN 2L
#undef gnu_io_I2CPort_PARITY_MARK
#define gnu_io_I2CPort_PARITY_MARK 3L
#undef gnu_io_I2CPort_PARITY_SPACE
#define gnu_io_I2CPort_PARITY_SPACE 4L
#undef gnu_io_I2CPort_STOPBITS_1
#define gnu_io_I2CPort_STOPBITS_1 1L
#undef gnu_io_I2CPort_STOPBITS_1_5
#define gnu_io_I2CPort_STOPBITS_1_5 0L
#undef gnu_io_I2CPort_STOPBITS_2
#define gnu_io_I2CPort_STOPBITS_2 2L
#undef gnu_io_I2CPort_FLOWCONTROL_NONE
#define gnu_io_I2CPort_FLOWCONTROL_NONE 0L
#undef gnu_io_I2CPort_FLOWCONTROL_RTSCTS_IN
#define gnu_io_I2CPort_FLOWCONTROL_RTSCTS_IN 1L
#undef gnu_io_I2CPort_FLOWCONTROL_RTSCTS_OUT
#define gnu_io_I2CPort_FLOWCONTROL_RTSCTS_OUT 2L
#undef gnu_io_I2CPort_FLOWCONTROL_XONXOFF_IN
#define gnu_io_I2CPort_FLOWCONTROL_XONXOFF_IN 4L
#undef gnu_io_I2CPort_FLOWCONTROL_XONXOFF_OUT
#define gnu_io_I2CPort_FLOWCONTROL_XONXOFF_OUT 8L
#ifdef __cplusplus
}
#endif
#endif
