/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_io_UnSupportedLoggerException */

#ifndef _Included_gnu_io_UnSupportedLoggerException
#define _Included_gnu_io_UnSupportedLoggerException
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_io_UnSupportedLoggerException_serialVersionUID
#define gnu_io_UnSupportedLoggerException_serialVersionUID -3042686055658047285LL
#undef gnu_io_UnSupportedLoggerException_serialVersionUID
#define gnu_io_UnSupportedLoggerException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
