/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_awt_GridLayout */

#ifndef _Included_java_awt_GridLayout
#define _Included_java_awt_GridLayout
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_GridLayout_serialVersionUID
#define java_awt_GridLayout_serialVersionUID -7411804673224730901LL
#ifdef __cplusplus
}
#endif
#endif
