/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_util_HashMap_HashIterator */

#ifndef _Included_java_util_HashMap_HashIterator
#define _Included_java_util_HashMap_HashIterator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
