/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_awt_event_WindowAdapter */

#ifndef _Included_java_awt_event_WindowAdapter
#define _Included_java_awt_event_WindowAdapter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
