/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_IndexOutOfBoundsException */

#ifndef _Included_java_lang_IndexOutOfBoundsException
#define _Included_java_lang_IndexOutOfBoundsException
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_IndexOutOfBoundsException_serialVersionUID
#define java_lang_IndexOutOfBoundsException_serialVersionUID -3042686055658047285LL
#undef java_lang_IndexOutOfBoundsException_serialVersionUID
#define java_lang_IndexOutOfBoundsException_serialVersionUID -3387516993124229948LL
#undef java_lang_IndexOutOfBoundsException_serialVersionUID
#define java_lang_IndexOutOfBoundsException_serialVersionUID -7034897190745766939LL
#ifdef __cplusplus
}
#endif
#endif
