/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_awt_Panel_AccessibleAWTPanel */

#ifndef _Included_java_awt_Panel_AccessibleAWTPanel
#define _Included_java_awt_Panel_AccessibleAWTPanel
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_Panel_AccessibleAWTPanel_serialVersionUID
#define java_awt_Panel_AccessibleAWTPanel_serialVersionUID 642321655757800191LL
#undef java_awt_Panel_AccessibleAWTPanel_serialVersionUID
#define java_awt_Panel_AccessibleAWTPanel_serialVersionUID 5081320404842566097LL
#undef java_awt_Panel_AccessibleAWTPanel_serialVersionUID
#define java_awt_Panel_AccessibleAWTPanel_serialVersionUID -6409552226660031050LL
#ifdef __cplusplus
}
#endif
#endif
