/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_awt_Panel */

#ifndef _Included_java_awt_Panel
#define _Included_java_awt_Panel
#ifdef __cplusplus
extern "C" {
#endif
#undef java_awt_Panel_FOCUS_TRAVERSABLE_UNKNOWN
#define java_awt_Panel_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef java_awt_Panel_FOCUS_TRAVERSABLE_DEFAULT
#define java_awt_Panel_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef java_awt_Panel_FOCUS_TRAVERSABLE_SET
#define java_awt_Panel_FOCUS_TRAVERSABLE_SET 2L
#undef java_awt_Panel_TOP_ALIGNMENT
#define java_awt_Panel_TOP_ALIGNMENT 0.0f
#undef java_awt_Panel_CENTER_ALIGNMENT
#define java_awt_Panel_CENTER_ALIGNMENT 0.5f
#undef java_awt_Panel_BOTTOM_ALIGNMENT
#define java_awt_Panel_BOTTOM_ALIGNMENT 1.0f
#undef java_awt_Panel_LEFT_ALIGNMENT
#define java_awt_Panel_LEFT_ALIGNMENT 0.0f
#undef java_awt_Panel_RIGHT_ALIGNMENT
#define java_awt_Panel_RIGHT_ALIGNMENT 1.0f
#undef java_awt_Panel_serialVersionUID
#define java_awt_Panel_serialVersionUID -7644114512714619750LL
#undef java_awt_Panel_serialVersionUID
#define java_awt_Panel_serialVersionUID 4613797578919906343LL
#undef java_awt_Panel_INCLUDE_SELF
#define java_awt_Panel_INCLUDE_SELF 1L
#undef java_awt_Panel_SEARCH_HEAVYWEIGHTS
#define java_awt_Panel_SEARCH_HEAVYWEIGHTS 1L
#undef java_awt_Panel_serialVersionUID
#define java_awt_Panel_serialVersionUID -2728009084054400034LL
#ifdef __cplusplus
}
#endif
#endif
